name: qikipay
description: A stylish and secure mobile wallet app
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core & Services
  firebase_core: ^2.30.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.3.0
  firebase_messaging: ^14.9.0
  firebase_remote_config: ^4.3.0
  flutter_local_notifications: ^16.1.0

  # State Management
  provider: ^6.1.1

  # UI & Design
  google_fonts: ^6.2.0
  flutter_animate: ^4.2.0
  animations: ^2.0.8
  fl_chart: ^0.65.0
  shimmer: ^3.0.0
  lottie: ^3.0.0

  # Utility & Formatting
  intl: ^0.18.1
  uuid: ^4.1.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.3
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  permission_handler: ^11.3.0

  # Navigation
  go_router: ^14.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
