name: qikipay
description: A stylish and secure mobile wallet app
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core & Services
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0
  firebase_remote_config: ^6.0.0
  flutter_local_notifications: ^19.4.0

  # State Management
  provider: ^6.1.1

  # UI & Design
  google_fonts: ^6.2.0
  flutter_animate: ^4.2.0
  animations: ^2.0.8
  fl_chart: ^1.0.0
  shimmer: ^3.0.0
  lottie: ^3.0.0

  # Utility & Formatting
  intl: ^0.20.2
  uuid: ^4.1.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.3
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  permission_handler: ^12.0.1

  # Navigation
  go_router: ^16.0.0

  # Additional dependencies to fix errors
  logger: ^2.6.1
  http: ^1.4.0
  qr_flutter: ^4.0.0
  mockito: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  fake_cloud_firestore: ^4.0.0

flutter:
  assets:
    - lib/assets/images/logo.png
    - lib/assets/images/
